### PR TITLE
EG-specific changes

### PR DESCRIPTION
**Pull request by danstaines**
Modification to EG-specific test group and addition of a Maven pom to allow reuse of HC code in another Java project

### CODE REVIEW

**Comment by magaliruffier** [comment]
the healthchecks seem to struggle with the Maven dependency
did you have to install something to get it working?

**Comment by danstaines** [comment]
On 06/07/15 11:43, Magali Ruffier wrote:
> the healthchecks seem to struggle with the Maven dependency
> did you have to install something to get it working?

not sure what you mean. Unless you explicitly run maven, this shouldn't 
make any difference. I just added this so I can build a jar and put it 
in a local repo for use by another project that uses maven.

-- 
Dan Staines, PhD               Ensembl Genomes Technical Coordinator
EMBL-EBI                       Tel: +44-(0)1223-492507
Wellcome Trust Genome Campus   Fax: +44-(0)1223-494468
Cambridge CB10 1SD, UK         http://www.ensemblgenomes.org/

**Comment by nerdstrike** [comment]
Travis he say:
Failure to find antlr:stringtemplate:jar:3.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by danstaines** [comment]
On 06/07/15 11:50, Kieron Taylor wrote:
> Travis he say:
> Failure to find antlr:stringtemplate:jar:3.0 in
> http://repo.maven.apache.org/maven2 was cached in the local repository,
> resolution will not be reattempted until the update interval of central
> has elapsed or updates are forced -> [Help 1]

to which I say, travis, mind your own business :-)

Adding this to .m2/settings.xml repositories this should sort it:
         <repository>
           <id>repository.jboss.org-public</id>
           <name>JBoss repository</name>
 
<url>https://repository.jboss.org/nexus/content/groups/public</url>
         </repository>


-- 
Dan Staines, PhD               Ensembl Genomes Technical Coordinator
EMBL-EBI                       Tel: +44-(0)1223-492507
Wellcome Trust Genome Campus   Fax: +44-(0)1223-494468
Cambridge CB10 1SD, UK         http://www.ensemblgenomes.org/

**Comment by magaliruffier** [comment]
I am not sure where those repositories are meant to be
Is it something you can add to the pull request?

**Comment by danstaines** [comment]
Not sure. Repositories get listed in your central maven config file. Not 
sure if they can be added to the pom.xml file

**Comment by danstaines** [comment]
Have added extra repos to pom.xml, waiting to see what Travis has to say for himself.

**Comment by nerdstrike** [comment]
Close but no banana! java.lang.ClassNotFoundException: org.h2.Driver

**Comment by danstaines** [comment]
Gah. Travis is being helpful and running any tests it can find when it runs the pom. Unfortunately, these tests fail, but I've no idea why as I didn't write them. Who maintains these tests?

**Comment by danstaines** [comment]
OK, looking at this, travis needs to cp database.defaults.properties to database.properties before running the maven build. Is this something that can be configured?

**Comment by nerdstrike** [comment]
Some pre-launch stuff can be ordered, see https://github.com/Ensembl/ensembl/blob/release/80/.travis.yml

**Comment by magaliruffier** [comment]
we should not be using database.properties file anywhere though
It is being set in ensj-healthcheck/test/src/org/ensembl/healthcheck/test/UtilsTest.java
        Assert.assertNotNull(Utils.readSimplePropertiesFile("database.properties"));
Can you try replacing that with database.default.properties and see if that makes travis happier?

**Comment by danstaines** [comment]
I think Travis is failing to compile with jdk6. jdk6 reached end of life 2 years ago, and I don't think we should try and support it. Can we remove jdk6 from the travis config?

**Comment by magaliruffier** [comment]
there was a time when healthchecks did not compile with jdk1.7 and we had to stick to jdk1.6, but that seems fine now
I've removed jdk6 from the travis config, you can rebase your changes against master, or we can pull the changes as is as travis is happy with the other versions

**Comment by danstaines** [comment]
I'll rebase the branch and resubmit a pull req...

**Comment by magaliruffier** [comment]
Travis is happy, victory :-)

**Pull request merged**
