### PR TITLE
Adding DensityFeatures to EGCoreIntegrity

### PR DESCRIPTION
**Pull request by dbolser-ebi**
I think this belongs here... Is EGCoreHandover built from this group, or should I also add it there?

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
I'd like to assign a reviewer, but I can't... @james-monkeyshines ?

**Comment by james-monkeyshines** [comment]
The change looks fine to me, thanks; the handover group inherits from this one, so no need to add there... **but**, you've submitted this against the "mater" branch. Which looks to be a typo of "master" that was inadvertently created last year. I'll try and untangle what's gone on there and delete the "mater" branch in due course, but in the meantime I think I should be able to do a manual merge against "master".

**Comment by james-monkeyshines** [comment]
Change pushed to master.

**Comment by dbolser-ebi** [comment]
Thanks. As far as git typos' go, at least that one's intelligible... I
usually create branches called 'origin/master' which confused the hell out
of me!

Cheers,

**Pull request closed without merging**
