### PR TITLE
Release/80

### PR DESCRIPTION
**Pull request by dbolser-ebi**
One minor change, one conceptual change.

### CODE REVIEW

**Comment by magaliruffier** [comment]
do these changes need to be on branch 80 or can they be merged onto master instead?
no problem with the second change
for the first one, as this is an eg hc, I'll let @james-monkeyshines or @danstaines comment

**Comment by james-monkeyshines** [comment]
I think I disagree about adding analysis_id to the group by statement.

Looking at a couple of plant core dbs, I assume that the motivation for this is where we have GO terms from multiple sources, and want to note that something is, for example, annotated via InterPro and projection from a reference species. But isn't the way to represent that to have multiple ontology_xref rows? That's the only mechanism I know of that would then display in the 'Annotation Source' column in the GO table in the browser. Having different analysis_ids might be useful for us, but is largely invisisble to the user (I think?)

It wouldn't be an issue, but adding analysis_id to the group by masks genuine problems. For example, in the Amborella trichopoda core on stg-1 there are UniPathway xrefs that have been annotated via Genome Loader and via InterProscan; if the analysis_id were added, these would not be detected.

**Comment by dbolser-ebi** [comment]
Sorry for ignorance, but wouldn't multiple ontology_xref rows create
multiple object_xref rows in turn? Perhaps we can refine the test to only
count duplicate object_xrefs that are not ontology_xrefs? Seems this would
pick up genuine problems but hide identical ontology terms from different
sources.

**Comment by james-monkeyshines** [comment]
Multiple ontology_xref rows can indeed create multiple object_xref rows (although not necessarily, since they could share an object_xref_id). So yes, the test could perhaps be refined to include an outer join onto ontology_xref, rather than using the analysis_id?

**Comment by dbolser-ebi** [comment]
OK, I'll have a look at doing that.
​

**Pull request closed without merging**
