### PR TITLE
Moving test to the right group.

### PR DESCRIPTION
**Pull request by mateuspatricio**

### CODE REVIEW

**Comment by muffato** [comment]
@marcoooo : will you merge `release/96` into `master` later ?

**Comment by marcoooo** [comment]
@muffato Was waiting for your approval first.

**Comment by mateuspatricio** [comment]
I didn't see the code was using tabs, I use spaces by default.

**Comment by marcoooo** [comment]
@mateuspatricio @muffato can you correct compilation errors?

**Comment by muffato** [comment]
In that case @mateuspatricio , please fix the indentation as well

**Pull request merged**
