### PR TITLE
mysql-ensembl-mirror has been renamed

### PR DESCRIPTION
**Pull request by muffato**
But the config file had not been updated

### CODE REVIEW

**Comment by marcoooo** [comment]
> But the config file had not been updated

Is it blocking your handover somehow?  I mean does it absolutely need to be merged in 98?

**Comment by muffato** [comment]
I don't think it is. The renaming happened a few releases ago, so we would have faced it already.
I needed that locally, though.

I can submit the PR on `master` if you prefer

**Comment by marcoooo** [comment]
> I don't think it is. The renaming happened a few releases ago, so we would have faced it already.
> I needed that locally, though.
> 
> I can submit the PR on `master` if you prefer

Yes please, mainly because current build fails on this branches because of oraclejdk late disclosure updates (you need to login to download oracle jdk now, so travis can't use it anymore out of the box). 
And since this is not particularly relevant to this release, I'd prefer to limit PR on release branch to the blocking bugs. Thank you for your understanding.

**Comment by muffato** [comment]
The PR is now on `master`

**Pull request merged**
